# Site
name: '晴霄财务记账报税'
description: '专注中小企业记账报税，创建企业，企业报税，企业月报、年报等'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'huangdh3@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           mikco 小帽
      site:           
      avatar:         ./assets/images/avatar1.webp
      bio:            "企业创建"
      email:         
      twitter:        

    jane:
      name:           yukie 爱猫你
      site:          
      avatar:         ./assets/images/avatar2.webp
      bio:            "企业记账报税"
      email:          
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: ./assets/images/avatar1.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]